name: mirrorfly_uikit_plugin
description: A Mirrorfly Flutter UIKit plugin to Experience an outstanding real time messaging solution. The powerful communication that adds an extra mileage to build your chat app.
version: 0.0.5
homepage: "https://www.mirrorfly.com/docs/UIKit/flutter/quick-start/"

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  mirrorfly_plugin: 0.0.7
  plugin_platform_interface: ^2.0.2
  flutter_svg: ^1.1.5
  cached_network_image: ^3.2.2
  file_picker: ^5.2.0+1 #file picker
  fluttertoast: ^8.0.7 #toast
  intl: ^0.17.0 #datetime
  package_info_plus: ^4.0.2 #package info
  image_picker: ^0.8.6
  flutter_profile_picture: ^2.0.0
  permission_handler: ^10.2.0
  emoji_picker_flutter: 1.4.0
  image_cropping: ^0.0.13 #crop image
  path_provider: ^2.0.11 #path provider
  video_player: ^2.4.7
  lottie: ^1.4.3
  url_launcher: ^6.1.6 #url Launcher
  custom_image_crop: ^0.0.4 #crop image
  photo_view: ^0.14.0
  fluttercontactpicker: ^4.7.0
  audioplayers: 4.1.0
  contacts_service: ^0.6.3
  google_maps_flutter: ^2.2.1 #google map
  geolocator: ^9.0.2 #geolocator
  geocoding: ^2.0.5 #geocoder for address
  focus_detector: ^2.0.1 #focus detector
  record: ^3.0.0
  swipe_to: ^1.0.2
  flutter_keyboard_visibility: ^5.4.0
  keyboard_dismisser: ^3.0.0
  scrollable_positioned_list: ^0.3.5 #scrollable position
  marquee: ^2.2.0 # marquee text
  path: ^1.8.2
  camera: ^0.10.5+2
  internet_connection_checker: ^1.0.0+1 # connectivity check
  provider: ^6.0.3
  photo_manager: ^2.5.2
  oktoast: ^3.3.1
  grouped_list: ^5.1.2
  share_plus: ^7.0.2
  flutter_local_notifications: ^13.0.0
  flutter_libphonenumber: ^1.4.0
  open_file_plus: ^3.4.0
  device_info_plus: ^8.1.0
  flutter_switch: ^0.3.2 #switchbox
  qr_code_scanner: ^1.0.1 #qr scanner
  yaml: ^3.1.1
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.mirrorfly.uikit_plugin.mirrorfly_uikit_plugin
        pluginClass: MirrorflyUikitPlugin
      ios:
        pluginClass: MirrorflyUikitPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - lib/assets/countries.txt
    - lib/assets/languages.txt
    - lib/assets/logos/
    - lib/assets/animation/
    - assets/countries.txt
    - assets/languages.txt
    - assets/logos/register_logo.svg
    - assets/animation/
    - pubspec.yaml
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
