name: mirrorfly_uikit_plugin
description: A Mirrorfly Flutter UIKit plugin to Experience an outstanding real time messaging solution. The powerful communication that adds an extra mileage to build your chat app.
version: 2.0.0
homepage: "https://www.mirrorfly.com/docs/UIKit/flutter/quick-start/"

environment:
  sdk: '>=2.19.2 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.2.2
  plugin_platform_interface: ^2.0.2
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  file_picker: ^8.0.6
  fluttertoast: ^8.2.6
  intl: ^0.19.0
  package_info_plus: ^8.0.0
  image_picker: ^1.1.2
#  flutter_profile_picture: ^2.0.0
  permission_handler: ^11.3.1
  emoji_picker_flutter: ^2.2.0
  path_provider: ^2.1.3
  video_player: ^2.9.1
  lottie: ^3.1.2
  url_launcher: ^6.3.0
  custom_image_crop: ^0.0.13
  photo_view: ^0.15.0
  audioplayers: ^6.0.0
  contacts_service: ^0.6.3
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  focus_detector: ^2.0.1 #focus detector
  record: ^5.1.2
  swipe_to: ^1.0.6
  flutter_keyboard_visibility: ^6.0.0
  keyboard_dismisser: ^3.0.0 #check and remove
  scrollable_positioned_list: ^0.3.8 #scrollable position
#  marquee: ^2.2.3 # marquee text
  path: ^1.9.0
  camera: ^0.11.0+1
  internet_connection_checker: ^1.0.0+1 # connectivity check
  provider: ^6.1.2
  photo_manager: ^3.2.1
  oktoast: ^3.4.0
  share_plus: ^9.0.0
  flutter_libphonenumber: ^2.2.2 # This depends on js lib 0.6.3, the same needed for qr code scanner, inApp web view
  open_file_plus: ^3.4.1+1
  device_info_plus: ^10.1.0
  flutter_switch: ^0.3.2 #switchbox
  qr_code_scanner: ^1.0.1 #qr scanner
  yaml: ^3.1.2
  shared_preferences: ^2.2.3
  tuple: ^2.0.2
  otp_text_field: ^1.1.3
  fading_edge_scrollview: ^4.1.1
  mirrorfly_plugin: ^1.0.5
#  mirrorfly_plugin:
#    path: ../p078-mirrorfly-flutter-plugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  lints: ^2.1.1

flutter:
  plugin:
    platforms:
      android:
        package: com.mirrorfly.uikit_plugin.mirrorfly_uikit_plugin
        pluginClass: MirrorflyUikitPlugin
      ios:
        pluginClass: MirrorflyUikitPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - lib/assets/countries.txt
    - lib/assets/languages.txt
    - lib/assets/logos/
    - lib/assets/calls/
    - lib/assets/animation/
    - assets/countries.txt
    - assets/languages.txt
    - assets/logos/register_logo.svg
    - assets/animation/
    - lib/assets/locales/
    - pubspec.yaml
