name: mirrorfly_uikit_plugin
description: A Mirrorfly Flutter UIKit plugin to Experience an outstanding real time messaging solution. The powerful communication that adds an extra mileage to build your chat app.
version: 1.0.0
homepage: "https://www.mirrorfly.com/docs/uikit/flutter/quick-start/"

environment:
  sdk: '>=2.19.2 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  mirrorfly_plugin: ^1.0.0
  http: ^1.1.0
  plugin_platform_interface: ^2.1.8
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  file_picker: ^8.0.0+1
  fluttertoast: ^8.2.4
  intl: ^0.19.0
  package_info_plus: ^6.0.0
  image_picker: ^1.0.7
  permission_handler: ^11.3.1
  emoji_picker_flutter: ^2.1.1
  path_provider: ^2.1.2
  video_player: ^2.8.5
  lottie: ^3.1.0
  url_launcher: ^6.2.5
  custom_image_crop: ^0.0.13
  photo_view: ^0.14.0
  fluttercontactpicker: ^4.7.0
  audioplayers: ^6.0.0
  contacts_service: ^0.6.3
  google_maps_flutter: ^2.6.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  focus_detector: ^2.0.1
  record: ^5.0.5
  swipe_to: ^1.0.6
  flutter_keyboard_visibility: ^6.0.0
  keyboard_dismisser: ^3.0.0
  scrollable_positioned_list: ^0.3.8
  marquee: ^2.2.3
  path: ^1.9.0
  camera: ^0.10.5+9
  internet_connection_checker: ^1.0.0+1
  provider: ^6.1.2
  photo_manager: ^3.0.0
  oktoast: ^3.4.0
  share_plus: ^8.0.2
  flutter_libphonenumber: ^2.2.1
  open_file_plus: ^3.4.1+1
  device_info_plus: ^10.0.1
  flutter_switch: ^0.3.2
  qr_code_scanner: ^1.0.1
  yaml: ^3.1.2
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.0.0
  tuple: ^2.0.2
  flutter_app_badger: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
#  lints: ^2.1.1

flutter:
  plugin:
    platforms:
      android:
        package: com.mirrorfly.uikit_plugin.mirrorfly_uikit_plugin
        pluginClass: MirrorflyUikitPlugin
      ios:
        pluginClass: MirrorflyUikitPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - lib/assets/countries.txt
    - lib/assets/languages.txt
    - lib/assets/logos/
    - lib/assets/calls/
    - lib/assets/animation/
    - assets/countries.txt
    - assets/languages.txt
    - assets/logos/register_logo.svg
    - assets/animation/
    - pubspec.yaml
